name: Deploy Admin Panel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code via SSH
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ADMIN }}

      - name: Set up SSH and deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_ADMIN }}" > ~/.ssh/id_ed25519_admin
          chmod 600 ~/.ssh/id_ed25519_admin

          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.SERVER_IP_ADMIN }} >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_ed25519_admin -o StrictHostKeyChecking=no ${{ secrets.USERNAME_ADMIN }}@${{ secrets.SERVER_IP_ADMIN }} << 'EOF'
            set -e
            sudo rm -rf /var/www/html/z-tv/admin-panel
            sudo git clone git@github.com:Zyacom/ZyacomtvAdminPanel.git /var/www/html/z-tv/admin-panel
            cd /var/www/html/z-tv/admin-panel
            sudo chown -R $USER:$USER .
            npm ci
            npx vite build --base=/admin/
            sudo mv dist/* ./
            sudo rm -rf dist
            sudo nginx -t && sudo systemctl reload nginx
            echo "Admin panel deployed successfully."
          EOF
