name: Deploy Admin Panel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Admin Panel
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USERNAME_ADMIN }}@${{ secrets.SERVER_IP_ADMIN }} << 'EOF'
            # Remove old folder
            sudo rm -rf /var/www/html/z-tv/admin-panel

            # Clone using the admin key already on the server
            sudo GIT_SSH_COMMAND='ssh -i ~/.ssh/id_ed25519_admin -o StrictHostKeyChecking=no' \
            git clone git@github.com:Zyacom/ZyacomtvAdminPanel.git /var/www/html/z-tv/admin-panel

            cd /var/www/html/z-tv/admin-panel || exit 1
            npm install
            npx vite build --base=/admin/
            sudo rm -rf *
            sudo mv dist/* ./
            sudo rm -rf dist
            sudo nginx -t && sudo systemctl reload nginx
            echo "Admin panel deployed successfully."
          EOF
